### PR TITLE
Simplify support of 32-bit architectures

### PR DESCRIPTION
**Pull request by Bodigrim**
https://github.com/klapaucius/vector-hashtables/blob/11a161fcf6927e960042377e3386771cc4c131e6/vector-hashtables.cabal#L30-L33
isn't really sufficient: there are more 32-bit architectures such as ARM and such.

But also it seems we can simplify the setup without losing anything, no?

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Great idea! There a little issue in the CI.

**Comment by Bodigrim** [comment]
@ulysses4ever fixed now.

**Review by ulysses4ever — APPROVED** [review]

**Comment by Bodigrim** [comment]
@ulysses4ever @swamp-agr any more comments / suggestions on this?

**Comment by ulysses4ever** [comment]
Thank you!

**Pull request merged**
